spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/groupbuy
spring.datasource.username=groupbuy
spring.datasource.password=groupbuy

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.jpa.show-sql=true